export const data_users = [
    {
        ID: 1,
        Name: 'Santiago Ruiz',
        Email: 'santiago.ruiz1991@gmail.com',
        BirthDate: '1990-01-01',
        ProfilePicture: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Oliver',
        GithubURL: 'https://github.com/santiagot',
        LinkedinURL: 'https://linkedin.com/in/santiagot',
        PitchVideo: 'https://example.com/pitch.mp4',
        Headline: 'Senior Software Developer',
        Bio: 'Experienced software developer with 10+ years of industry experience.',
        Seniority: '10+ years',
        EnglishLevel: 'Advanced',
        EFSetScore: '75',
        Points: 1250,
        Role: 'developer',
        Country: 'CO',
        Availability: 'Full-time',
        Interests: 'JavaScript, Typescript, Angular',
        Status: true,
    },
    {
        ID: 2,
        Name: 'Juan Pérez',
        Email: 'juan.perez@gmail.com',
        BirthDate: '1985-05-10',
        ProfilePicture: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Sophie',
        GithubURL: 'https://github.com/juanperez',
        LinkedinURL: 'https://linkedin.com/in/juanperez',
        PitchVideo: 'https://example.com/pitch.mp4',
        Headline: 'Frontend Developer',
        Bio: 'Experienced frontend developer with 5+ years of industry experience.',
        Seniority: '5+ years',
        EnglishLevel: 'Intermediate',
        EFSetScore: '60',
        Points: 1000,
        Role: 'developer',
        Country: 'CO',
        Availability: 'Full-time',
        Interests: 'React, Vue, Angular',
        Status: true,
    },
    {
        ID: 3,
        Name: 'María López',
        Email: 'maria.lopez@gmail.com',
        BirthDate: '1995-08-15',
        ProfilePicture: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Ava',
        GithubURL: 'https://github.com/marialopez',
        LinkedinURL: 'https://linkedin.com/in/marialopez',
        PitchVideo: 'https://example.com/pitch.mp4',
        Headline: 'UI/UX Designer',
        Bio: 'Experienced UI/UX designer with 3+ years of industry experience.',
        Seniority: '3+ years',
        EnglishLevel: 'Intermediate',
        EFSetScore: '70',
        Points: 1100,
        Role: 'designer',
        Country: 'CO',
        Availability: 'Full-time',
        Interests: 'Figma, Sketch, Adobe XD',
        Status: true,
    },
    {
        ID: 4,
        Name: 'Pedro Gómez',
        Email: 'pedro.gomez@gmail.com',
        BirthDate: '1990-03-20',
        ProfilePicture: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Max',
        GithubURL: 'https://github.com/pedrogomez',
        LinkedinURL: 'https://linkedin.com/in/pedrogomez',
        PitchVideo: 'https://example.com/pitch.mp4',
        Headline: 'Product Manager',
        Bio: 'Experienced product manager with 2+ years of industry experience.',
        Seniority: '2+ years',
        EnglishLevel: 'Intermediate',
        EFSetScore: '75',
        Points: 1150,
        Role: 'product',
        Country: 'CO',
        Availability: 'Full-time',
        Interests: 'Agile, User Research, Product Strategy',
        Status: true,
    },
    {
        ID: 5,
        Name: 'Ana Rodríguez',
        Email: 'ana.rodriguez@gmail.com',
        BirthDate: '1995-12-05',
        ProfilePicture: 'https://api.dicebear.com/9.x/adventurer/svg?seed=Ella',
        GithubURL: 'https://github.com/anarodriguez',
        LinkedinURL: 'https://linkedin.com/in/anarodriguez',
        PitchVideo: 'https://example.com/pitch.mp4',
        Headline: 'Product Manager',
        Bio: 'Experienced product manager with 2+ years of industry experience.',
        Seniority: '2+ years',
        EnglishLevel: 'Junior',
        EFSetScore: '75',
        Points: 1150,
        Role: 'product',
        Country: 'CO',
        Availability: 'Full-time',
        Interests: 'Agile, User Research, Product Strategy',
        Status: true,
    }
]